#! /bin/bash

user_number=()

if [ $# -eq 0 ]; then
	read -p "Enter number: " user_number 
else
	user_number=$1
fi


random_number=()

get_random_number(){
	random_number=$(($RANDOM % 6))
}

compare(){
if [ $random_number -gt $user_number ]; then
	echo "$random_number is greater than $user_number"
elif [ $random_number -lt $user_number ]; then 

	echo "$random_number is less than $user_number"
else
	echo "$random_number is equal to $user_number"
fi
}


get_random_number
compare






